     var floatYears, floatMonths, floatFortnights, floatWeeks, floatDays;
     floatYears = prompt("Enter current age");
     floatMonths = floatYears*12;
     floatFortnights = floatYears*26.08875;
     floatWeeks = floatYears*52;
     floatDays = floatYears*365;
     alert("Age in months = " + floatMonths);
     alert("Age in fortnights = " + floatFortnights);
     alert("Age in weeks = " + floatWeeks);
     alert("Age in days = " + floatDays);